### ISSUE TITLE
Capture and report all validation errors on model translation

### ISSUE THREAD

**Issue by macumber** [ladybug-tools-in2/energy-model-measure#3]

**Comment by chriswmackey** [comment]
We can leave this open but, the more that I think about it, the more it seems that it shouldn't be the measure's responsibility to validate the input. Validation can happen through Python libraries when it comes to the cloud service and, as long as the measure raises meaningful exceptions when it sense that an input is not valid, that should be all that is necessary.  In other words, the measure should take an [eafp approach rather than a lbyl one](https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/).

**Comment by chriswmackey** [comment]
I just wanted to post an update that we decided the validations should be optional, particularly now that I see how incredibly long the measure takes to run.  For this reason, I think that, whenever we are running the measure with a JSON from out plugins, we won't do the validation in the measure.

**Comment by chriswmackey** [comment]
I am going to close this for now. We have validation with pydantic working pretty well and I think this is what we would use if we needed to validate a JSON before we run it through the measure.
